#! /bin/bash

# stop script when an error occurs
set -e

psql -q -c "CREATE USER ebargain_admin SUPERUSER PASSWORD 'pass123'"
echo "Created Postgres user 'ebargain_admin'"

psql -q -c "CREATE DATABASE ebargain WITH OWNER ebargain_admin"
echo "Created Postgres database 'ebargain'"

cp example.env .env
echo "Created .env containing DATABASE_URL"